# security-deployment.yaml (updated)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service-deployment
spec:
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
      - name: security-service
        image: your-security-service-image
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: security-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: security-config
              key: Database_ConnectionString
        - name: JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: security-secret
              key: jwt-private-key
