# security-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: security-secret
type: Opaque
data:
  jwt-private-key: bW9oYW1lZGdvbTNhbW83YW1lZGE3bWVk  # base64 encoded "mohamedgom3amo7ameda7med"
