apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: default
type: Opaque
data:
  # Replace these values with base64-encoded strings
  MONGO_USERNAME: bW9uZ29fdXNlcg==   # base64 encoded username
  MONGO_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk   # base64 encoded password
  JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQkFqQU...   # base64 encoded public key


#echo -n 'your_value' | base64
