version: '3.8'

services:
  # .NET Service
  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Expose the port 5000 for the .NET app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=mongodb://mongo:27017/UserManagementDB
    depends_on:
      - mongo
    networks:
      - app-network

  # MongoDB Service
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: UserManagementDB
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: host

volumes:
  mongodb-data:
    driver: local
