# rabbitmq-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
type: Opaque
data:
  # Replace these values with base64-encoded strings
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q= # base64 encoded username
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q= # base64 encoded password
