# rabbitmq-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  RABBITMQ_ERLANG_COOKIE: "rabbitmq_cookie" # Replace this with your desired cookie
  RABBITMQ_DEFAULT_VHOST: "/"
  RABBITMQ_DEFAULT_USER: "guest" # Set this according to your needs
  RABBITMQ_DEFAULT_PASS: "guest" # Set this according to your needs
