# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: c29tZS1yb290LXBhc3N3b3Jk   # base64 encoded "some-root-password"
  mysql-user: dXNlcg==                            # base64 encoded "user"
  mysql-password: cGFzc3dvcmQ=                    # base64 encoded "password"
