# security-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Database_ConnectionString: "Server=mysql-service;Database=securitydb;User=user;Password=password;"
